events {
    worker_connections 1024;
}

http {
    ssl_certificate /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    ## reverse-proxy
    server {
        listen 80;
        server_name __REVERSE_PROXY_DOMAIN__;

        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name __REVERSE_PROXY_DOMAIN__;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }

    ## streaming
    server {
        listen 80;
        server_name __STREAMING_DOMAIN__;

        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name __STREAMING_DOMAIN__;

        location / {
            proxy_pass http://streaming:80;

            # CORS対策
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, OPTIONS';
            add_header Access-Control-Allow-Headers 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    ## api
    server {
        listen 80;
        server_name __API_DOMAIN__;

        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name __API_DOMAIN__;

        location / {
            proxy_pass http://api:5000;

            # CORS対策
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, OPTIONS';
            add_header Access-Control-Allow-Headers 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    ## front
    server {
        listen 80;
        server_name __FRONT_DOMAIN__;

        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        server_name __FRONT_DOMAIN__;

        location / {
            proxy_pass http://front:80;

            # CORS対策
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, OPTIONS';
            add_header Access-Control-Allow-Headers 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
